[package]
name = "observer"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.11"
ctrlc = { version = "3.4.5", features = ["termination"] }
env_logger = "0.11.6"
log = "0.4.26"
num_cpus = "1.16.0"
serde = "1.0.219"
sysinfo = "0.33.1"
