name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: observer
            name: observer-linux-amd64

    runs-on: ${{ matrix.platform.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.platform.target }}
          
      - name: Package Release
        shell: bash
        run: |
          mkdir -p release
          cp target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} release/
          cp install.sh release/
          cp observer.service release/
          cp config.toml release/
          cd release
          tar czf ../${{ matrix.platform.name }}.tar.gz *
          
      - name: Generate SHA256 checksum
        run: |
          cd ${{ github.workspace }}
          sha256sum ${{ matrix.platform.name }}.tar.gz > ${{ matrix.platform.name }}.sha256
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.platform.name }}.tar.gz
            ${{ matrix.platform.name }}.sha256